{
	"version": 1739941173,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/play-sheet0.png",
		"images/bg-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/frame-sheet0.png",
		"images/card-sheet0.png",
		"images/card-sheet1.png",
		"images/card-sheet2.png",
		"images/card-sheet3.png",
		"images/card-sheet4.png",
		"images/card-sheet5.png",
		"images/card-sheet6.png",
		"images/card-sheet7.png",
		"images/card-sheet8.png",
		"images/card-sheet9.png",
		"images/card-sheet10.png",
		"images/card-sheet11.png",
		"images/card-sheet12.png",
		"images/card-sheet13.png",
		"images/card-sheet14.png",
		"images/card-sheet15.png",
		"images/card-sheet16.png",
		"images/card-sheet17.png",
		"images/card-sheet18.png",
		"images/card-sheet19.png",
		"images/card-sheet20.png",
		"images/card-sheet21.png",
		"images/card-sheet22.png",
		"images/card-sheet23.png",
		"images/card-sheet24.png",
		"images/card-sheet25.png",
		"images/card-sheet26.png",
		"images/card-sheet27.png",
		"images/card-sheet28.png",
		"images/card-sheet29.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/swipe.m4a",
		"media/swipe.ogg",
		"media/result (1).m4a",
		"media/result (1).ogg",
		"media/bg (3).m4a",
		"media/bg (3).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}